import { defineGraph } from '../grantGraph'
import type { InterviewQuestion } from '../types'

const questions: InterviewQuestion[] = [
  {
    id: 'summary',
    formSection: 'Project description',
    formFieldLabel: 'Project summary',
    question: 'In a few sentences, what is this short-term mobility project about?',
    helpText: 'Name the organisations, the destination, who travels, and the professional need it answers.',
    type: 'textarea',
    next: 'org_type',
  },
  {
    id: 'org_type',
    formSection: 'Participating organisation',
    formFieldLabel: 'Organisation type',
    question: 'What type of organisation is applying?',
    type: 'select',
    options: [
      { value: 'school', label: 'School' },
      { value: 'vet', label: 'VET provider' },
      { value: 'adult', label: 'Adult education provider' },
    ],
    next: 'needs_school',
    branches: [
      { equals: 'school', goto: 'needs_school' },
      { equals: 'vet', goto: 'needs_vet' },
      { equals: 'adult', goto: 'needs_adult' },
    ],
  },
  {
    id: 'needs_school',
    formSection: 'Needs analysis',
    formFieldLabel: 'Identified needs',
    question: 'What needs at your school does this mobility respond to?',
    helpText: 'Reviewers want staff- or learner-level needs, not a generic “we want to internationalise”.',
    type: 'textarea',
    next: 'needs_method',
  },
  {
    id: 'needs_vet',
    formSection: 'Needs analysis',
    formFieldLabel: 'Identified needs',
    question: 'What needs in your VET provision does this mobility respond to?',
    type: 'textarea',
    next: 'needs_method',
  },
  {
    id: 'needs_adult',
    formSection: 'Needs analysis',
    formFieldLabel: 'Identified needs',
    question: 'What needs among your adult learners or staff does this mobility respond to?',
    type: 'textarea',
    next: 'needs_method',
  },
  {
    id: 'needs_method',
    formSection: 'Needs analysis',
    formFieldLabel: 'Needs method',
    question: 'How did you identify those needs?',
    helpText: 'Name the method, when you did it, and roughly how many people you asked.',
    type: 'select',
    options: [
      { value: 'survey', label: 'Staff / learner survey' },
      { value: 'focus', label: 'Focus groups or interviews' },
      { value: 'plan', label: 'From our development / quality plan' },
      { value: 'mixed', label: 'A mix of the above' },
    ],
    next: 'needs_evidence',
  },
  {
    id: 'needs_evidence',
    formSection: 'Needs analysis',
    formFieldLabel: 'What people actually said',
    question: 'What did staff or learners actually tell you? Quote or paraphrase the main findings.',
    type: 'textarea',
    next: 'partners',
  },
  {
    id: 'partners',
    formSection: 'Partnership',
    formFieldLabel: 'Host organisations',
    question: 'Do you already have a host organisation confirmed?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes, confirmed' },
      { value: 'some', label: 'In discussion' },
      { value: 'no', label: 'Not yet' },
    ],
    next: 'partner_names',
    branches: [
      { equals: 'yes', goto: 'partner_names' },
      { equals: 'some', goto: 'partner_search' },
      { equals: 'no', goto: 'partner_search' },
    ],
  },
  {
    id: 'partner_names',
    formSection: 'Partnership',
    formFieldLabel: 'Host organisation',
    question: 'Who is the host, in which country, and why this organisation?',
    type: 'textarea',
    next: 'destination',
  },
  {
    id: 'partner_search',
    formSection: 'Partnership',
    formFieldLabel: 'Host profile needed',
    question: 'What kind of host are you looking for, and in which country?',
    type: 'textarea',
    next: 'destination',
  },
  {
    id: 'destination',
    formSection: 'Activities',
    formFieldLabel: 'Destination',
    question: 'Which country will the mobility take place in, and why that venue?',
    helpText: 'The venue should normally be in a participating organisation’s country, with a reason.',
    type: 'textarea',
    next: 'participant_count',
  },
  {
    id: 'participant_count',
    formSection: 'Participants',
    formFieldLabel: 'Number of participants',
    question: 'How many participants do you plan to send?',
    type: 'text',
    next: 'participant_profile',
  },
  {
    id: 'participant_profile',
    formSection: 'Participants',
    formFieldLabel: 'Participant profile',
    question: 'Who are they (roles, seniority or year group), and how will you select them?',
    helpText: 'Name published selection criteria if you have them.',
    type: 'textarea',
    next: 'fewer_opportunities',
  },
  {
    id: 'fewer_opportunities',
    formSection: 'Participants',
    formFieldLabel: 'Fewer opportunities',
    question: 'Will any participants have fewer opportunities?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'Not in this flow' },
    ],
    next: 'mobility_type',
    branches: [
      { equals: 'yes', goto: 'inclusion_measures' },
      { equals: 'no', goto: 'mobility_type' },
    ],
  },
  {
    id: 'inclusion_measures',
    formSection: 'Participants',
    formFieldLabel: 'Inclusion measures',
    question: 'Which barriers, and what support will you put in place?',
    type: 'textarea',
    next: 'mobility_type',
  },
  {
    id: 'mobility_type',
    formSection: 'Activities',
    formFieldLabel: 'Type of mobility',
    question: 'What kind of mobility are you organising?',
    type: 'select',
    options: [
      { value: 'staff', label: 'Staff mobility' },
      { value: 'learners', label: 'Learner mobility' },
      { value: 'both', label: 'Both staff and learners' },
    ],
    next: 'activities_staff',
    branches: [
      { equals: 'staff', goto: 'activities_staff' },
      { equals: 'learners', goto: 'activities_learners' },
      { equals: 'both', goto: 'activities_both' },
    ],
  },
  {
    id: 'activities_staff',
    formSection: 'Activities',
    formFieldLabel: 'Planned activities',
    question: 'What will staff do (job shadowing, a course, teaching assignment)? Outline the programme.',
    type: 'textarea',
    next: 'duration',
  },
  {
    id: 'activities_learners',
    formSection: 'Activities',
    formFieldLabel: 'Planned activities',
    question: 'What will learners do during the mobility? Outline the programme day by day if you can.',
    type: 'textarea',
    next: 'duration',
  },
  {
    id: 'activities_both',
    formSection: 'Activities',
    formFieldLabel: 'Planned activities',
    question: 'Describe staff and learner activities separately, including a rough daily programme.',
    type: 'textarea',
    next: 'duration',
  },
  {
    id: 'duration',
    formSection: 'Activities',
    formFieldLabel: 'Duration and timeframe',
    question: 'When, and for how many days, will the mobility take place?',
    type: 'text',
    next: 'objectives',
  },
  {
    id: 'objectives',
    formSection: 'What & How',
    formFieldLabel: 'Objectives',
    question: 'List 3–5 SMART objectives that follow from the needs you described.',
    type: 'textarea',
    next: 'learning_outcomes',
  },
  {
    id: 'learning_outcomes',
    formSection: 'What & How',
    formFieldLabel: 'Learning outcomes',
    question: 'What knowledge, skills and attitudes should participants bring back into daily work?',
    type: 'textarea',
    next: 'preparation',
  },
  {
    id: 'preparation',
    formSection: 'What & How',
    formFieldLabel: 'Preparation',
    question: 'How will you prepare participants (pedagogical, cultural, practical, language)?',
    type: 'textarea',
    next: 'follow_up',
  },
  {
    id: 'follow_up',
    formSection: 'What & How',
    formFieldLabel: 'Follow-up',
    question: 'What happens after they return — who uses the learning, and how will you check it?',
    type: 'textarea',
    next: 'impact',
  },
  {
    id: 'impact',
    formSection: 'Impact',
    formFieldLabel: 'Expected impact',
    question: 'What change do you expect, for whom, and how will you know?',
    helpText: 'Name a beneficiary group, a measurable change, and a timeframe.',
    type: 'textarea',
    next: 'dissemination',
  },
  {
    id: 'dissemination',
    formSection: 'Impact',
    formFieldLabel: 'Dissemination',
    question: 'Who will you share results with, through which channels, and when?',
    type: 'textarea',
    next: 'risks',
  },
  {
    id: 'risks',
    formSection: 'Management',
    formFieldLabel: 'Risks',
    question: 'Name the main risks and a concrete mitigation for each.',
    type: 'textarea',
    next: 'added_value',
  },
  {
    id: 'added_value',
    formSection: 'Impact',
    formFieldLabel: 'European added value',
    question: 'Why does this need a European mobility, rather than a local training?',
    type: 'textarea',
    next: null,
  },
]

export const ka122Graph = defineGraph('summary', questions)
