import { defineGraph } from '../grantGraph'
import type { InterviewQuestion } from '../types'

const questions: InterviewQuestion[] = [
  {
    id: 'summary',
    formSection: 'Objectives and needs',
    formFieldLabel: 'Mobility plan summary',
    question: 'What mobility are you drawing down against your Erasmus accreditation this round?',
    helpText: 'KA121 is lighter than KA122: you are implementing an accredited plan, not justifying a project from scratch.',
    type: 'textarea',
    next: 'accreditation',
  },
  {
    id: 'accreditation',
    formSection: 'Management and accreditation',
    formFieldLabel: 'Accreditation',
    question: 'Do you hold a valid Erasmus accreditation for this field?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No — we may need KA122 instead' },
    ],
    next: 'field',
    factKey: 'accredited',
    ai: { canPropose: false, cannotInvent: true },
    branches: [
      { equals: 'yes', goto: 'field' },
      { equals: 'no', goto: 'field' },
    ],
  },
  {
    id: 'field',
    formSection: 'Objectives and needs',
    formFieldLabel: 'Education field',
    question: 'Which accredited field is this call for?',
    type: 'select',
    factKey: 'education_field',
    ai: { canPropose: false },
    options: [
      { value: 'school', label: 'School education' },
      { value: 'vet', label: 'Vocational education and training' },
      { value: 'adult', label: 'Adult education' },
    ],
    next: 'activity_mix',
  },
  {
    id: 'activity_mix',
    formSection: 'Activities and learning outcomes',
    formFieldLabel: 'Activity types',
    question: 'Which mobility activities are you requesting this year?',
    type: 'select',
    factKey: 'mobility_role',
    dependsOn: ['field'],
    ai: { canPropose: true, proposalStrategy: 'conservative' },
    options: [
      { value: 'staff', label: 'Staff only (courses, job shadowing, teaching)' },
      { value: 'learners', label: 'Learners only' },
      { value: 'both', label: 'Staff and learners' },
    ],
    next: 'staff_activities',
    branches: [
      { equals: 'staff', goto: 'staff_activities' },
      { equals: 'learners', goto: 'learner_activities' },
      { equals: 'both', goto: 'staff_activities' },
    ],
  },
  {
    id: 'staff_activities',
    formSection: 'Activities and learning outcomes',
    formFieldLabel: 'Staff activities',
    question: 'Describe the staff mobilities: type, host country, duration, and what they will do.',
    type: 'textarea',
    next: 'learner_gate',
    ai: { canPropose: false, cannotInvent: true },
  },
  {
    id: 'learner_gate',
    formSection: 'Activities and learning outcomes',
    formFieldLabel: 'Learner activities next',
    question: 'Are learner mobilities part of this request?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No, staff only' },
    ],
    next: 'destinations',
    branches: [
      { equals: 'yes', goto: 'learner_activities' },
      { equals: 'no', goto: 'destinations' },
    ],
  },
  {
    id: 'learner_activities',
    formSection: 'Activities and learning outcomes',
    formFieldLabel: 'Learner activities',
    question: 'Describe the learner mobilities: group size, host, duration, and programme.',
    type: 'textarea',
    next: 'destinations',
    factKey: 'mobility_format',
    dependsOn: ['activity_mix'],
    ai: { canPropose: true, proposalStrategy: 'conservative' },
  },
  {
    id: 'destinations',
    formSection: 'Activities and learning outcomes',
    formFieldLabel: 'Destinations',
    question: 'Which countries and host organisations, and why these hosts for your accredited objectives?',
    type: 'textarea',
    next: 'participant_count',
    factKey: 'destination_country',
    ai: { canPropose: false, cannotInvent: true, feasibilityCheck: true },
  },
  {
    id: 'participant_count',
    formSection: 'Participants',
    formFieldLabel: 'Numbers',
    question: 'How many staff and/or learners will travel in this call year?',
    type: 'text',
    next: 'selection',
    factKey: 'participant_count',
    dependsOn: ['activity_mix'],
    ai: { canPropose: true, proposalStrategy: 'conservative', feasibilityCheck: true },
  },
  {
    id: 'selection',
    formSection: 'Participants',
    formFieldLabel: 'Selection',
    question: 'How will you select participants against your accredited plan?',
    type: 'textarea',
    next: 'fewer_opportunities',
    factKey: 'selection_criteria',
    ai: { canPropose: true, requiresEvidence: true },
  },
  {
    id: 'fewer_opportunities',
    formSection: 'Participants',
    formFieldLabel: 'Fewer opportunities',
    question: 'How many participants with fewer opportunities, and what support is in place?',
    type: 'textarea',
    next: 'objectives',
    ai: { canPropose: false, cannotInvent: true },
  },
  {
    id: 'objectives',
    formSection: 'Activities and learning outcomes',
    formFieldLabel: 'Objectives this year',
    question: 'Which accredited objectives does this year’s mobility advance?',
    type: 'textarea',
    next: 'preparation',
    factKey: 'learner_need',
    ai: { canPropose: true, proposalStrategy: 'conservative', requiresEvidence: true },
  },
  {
    id: 'preparation',
    formSection: 'Activities and learning outcomes',
    formFieldLabel: 'Preparation and follow-up',
    question: 'How do you prepare participants and follow up so learning feeds into the organisation?',
    type: 'textarea',
    next: 'recognition',
    ai: { canPropose: true, proposalStrategy: 'conservative' },
  },
  {
    id: 'recognition',
    formSection: 'Recognition and follow-up',
    formFieldLabel: 'Recognition',
    question: 'How will learning be recognised (certificate, Europass, internal validation, sharing with colleagues)?',
    type: 'textarea',
    next: 'impact',
    ai: { canPropose: true, proposalStrategy: 'conservative' },
  },
  {
    id: 'impact',
    formSection: 'Recognition and follow-up',
    formFieldLabel: 'Expected impact',
    question: 'What organisational change should this year’s mobilities produce, and how will you see it?',
    type: 'textarea',
    next: 'dissemination',
    ai: { canPropose: true, requiresEvidence: true },
  },
  {
    id: 'dissemination',
    formSection: 'Recognition and follow-up',
    formFieldLabel: 'Sharing results',
    question: 'How will results be shared inside the organisation and with other accredited peers?',
    type: 'textarea',
    next: null,
    ai: { canPropose: true, proposalStrategy: 'conservative' },
  },
]

export const ka121Graph = defineGraph('summary', questions)
