import { defineGraph } from '../grantGraph'
import type { InterviewQuestion } from '../types'

const questions: InterviewQuestion[] = [
  {
    id: 'summary',
    formSection: 'Project description',
    formFieldLabel: 'Mobility summary',
    question: 'What higher-education mobility are you planning?',
    helpText: 'KA131 is between Programme-country institutions. KA171 covers mobility with Partner countries.',
    type: 'textarea',
    next: 'strand',
  },
  {
    id: 'strand',
    formSection: 'Participating organisation',
    formFieldLabel: 'Strand',
    question: 'Is this intra-Programme mobility (KA131) or mobility with Partner countries (KA171)?',
    type: 'select',
    options: [
      { value: 'ka131', label: 'KA131 — Programme countries' },
      { value: 'ka171', label: 'KA171 — Partner countries' },
    ],
    next: 'role',
  },
  {
    id: 'role',
    formSection: 'Participating organisation',
    formFieldLabel: 'Institution role',
    question: 'Is your institution sending, receiving, or both?',
    type: 'select',
    options: [
      { value: 'sending', label: 'Sending' },
      { value: 'receiving', label: 'Receiving' },
      { value: 'both', label: 'Both' },
    ],
    next: 'cycle',
  },
  {
    id: 'cycle',
    formSection: 'Participants',
    formFieldLabel: 'Who travels',
    question: 'Who will take part?',
    type: 'select',
    options: [
      { value: 'students', label: 'Students (studies or traineeship)' },
      { value: 'staff', label: 'Staff (teaching or training)' },
      { value: 'both', label: 'Students and staff' },
    ],
    next: 'student_mobility',
    branches: [
      { equals: 'students', goto: 'student_mobility' },
      { equals: 'staff', goto: 'staff_mobility' },
      { equals: 'both', goto: 'student_mobility' },
    ],
  },
  {
    id: 'student_mobility',
    formSection: 'Activities',
    formFieldLabel: 'Student mobility',
    question: 'Studies, traineeship, or blended? Cycle (BA/MA/PhD), duration, and expected ECTS.',
    type: 'textarea',
    next: 'staff_gate',
  },
  {
    id: 'staff_gate',
    formSection: 'Activities',
    formFieldLabel: 'Staff mobility next',
    question: 'Does this request also include staff mobility?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No, students only' },
    ],
    next: 'partners',
    branches: [
      { equals: 'yes', goto: 'staff_mobility' },
      { equals: 'no', goto: 'partners' },
    ],
  },
  {
    id: 'staff_mobility',
    formSection: 'Activities',
    formFieldLabel: 'Staff mobility',
    question: 'Teaching assignment or training? Host, duration, and what they will do.',
    type: 'textarea',
    next: 'partners',
  },
  {
    id: 'partners',
    formSection: 'Partnership',
    formFieldLabel: 'Partner institutions',
    question: 'Which HEIs are involved, in which countries, and do you have inter-institutional agreements?',
    type: 'textarea',
    next: 'numbers',
  },
  {
    id: 'numbers',
    formSection: 'Participants',
    formFieldLabel: 'Numbers',
    question: 'How many students and/or staff, and for how many days or months?',
    type: 'text',
    next: 'selection',
  },
  {
    id: 'selection',
    formSection: 'Participants',
    formFieldLabel: 'Selection and recognition',
    question: 'How will you select participants, and how will learning be recognised (learning agreement, ECTS, transcript)?',
    type: 'textarea',
    next: 'fewer_opportunities',
  },
  {
    id: 'fewer_opportunities',
    formSection: 'Participants',
    formFieldLabel: 'Inclusion',
    question: 'What inclusion support will you offer participants with fewer opportunities?',
    type: 'textarea',
    next: 'objectives',
  },
  {
    id: 'objectives',
    formSection: 'What & How',
    formFieldLabel: 'Objectives',
    question: 'What should this mobility achieve for students, staff, and the institution?',
    type: 'textarea',
    next: 'impact',
  },
  {
    id: 'impact',
    formSection: 'Impact',
    formFieldLabel: 'Impact',
    question: 'What change do you expect after return, and how will you know?',
    type: 'textarea',
    next: 'added_value',
  },
  {
    id: 'added_value',
    formSection: 'Impact',
    formFieldLabel: 'European added value',
    question: 'Why does this need Erasmus+ rather than a local placement or training?',
    type: 'textarea',
    next: null,
  },
]

export const ka131Graph = defineGraph('summary', questions)
