import { defineGraph } from '../grantGraph'
import type { InterviewQuestion } from '../types'

const questions: InterviewQuestion[] = [
  {
    id: 'summary',
    formSection: 'Project description',
    formFieldLabel: 'Project summary',
    question: 'What is this small-scale partnership about, in a few sentences?',
    helpText: 'KA210 is for newcomers and smaller organisations. Keep the partnership and budget proportionate.',
    type: 'textarea',
    next: 'experience',
  },
  {
    id: 'experience',
    formSection: 'Participating organisation',
    formFieldLabel: 'Experience',
    question: 'Is this your organisation’s first Erasmus+ partnership?',
    type: 'select',
    options: [
      { value: 'first', label: 'Yes, first time' },
      { value: 'some', label: 'We have some EU project experience' },
    ],
    next: 'partners',
  },
  {
    id: 'partners',
    formSection: 'Partnership',
    formFieldLabel: 'Partners',
    question: 'Do you already have partner organisations in another Programme country?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes, confirmed (at least one other country)' },
      { value: 'some', label: 'Some confirmed, still looking' },
      { value: 'no', label: 'Not yet' },
    ],
    next: 'partner_details',
    branches: [
      { equals: 'yes', goto: 'partner_details' },
      { equals: 'some', goto: 'partner_search' },
      { equals: 'no', goto: 'partner_search' },
    ],
  },
  {
    id: 'partner_details',
    formSection: 'Partnership',
    formFieldLabel: 'Partner organisations',
    question: 'Name the partners, countries, and why this consortium can deliver the work.',
    type: 'textarea',
    next: 'duration',
  },
  {
    id: 'partner_search',
    formSection: 'Partnership',
    formFieldLabel: 'Partner profile needed',
    question: 'What kind of partner are you looking for, in which country, and what should they bring?',
    type: 'textarea',
    next: 'duration',
  },
  {
    id: 'duration',
    formSection: 'Activities',
    formFieldLabel: 'Duration',
    question: 'How long will the project run (typically 6–24 months), and when would it start?',
    type: 'text',
    next: 'lump_sum',
  },
  {
    id: 'lump_sum',
    formSection: 'Management',
    formFieldLabel: 'Lump sum',
    question: 'Which KA210 lump-sum amount are you aiming for?',
    type: 'select',
    options: [
      { value: '30k', label: 'EUR 30 000' },
      { value: '60k', label: 'EUR 60 000' },
    ],
    next: 'priority',
  },
  {
    id: 'priority',
    formSection: 'Priorities',
    formFieldLabel: 'Priority',
    question: 'Which EU priority does the project address most directly?',
    type: 'select',
    options: [
      { value: 'inclusion', label: 'Inclusion and diversity' },
      { value: 'digital', label: 'Digital transformation' },
      { value: 'green', label: 'Environment and green transition' },
      { value: 'participation', label: 'Participation in democratic life' },
    ],
    next: 'needs',
  },
  {
    id: 'needs',
    formSection: 'Needs analysis',
    formFieldLabel: 'Needs',
    question: 'What need in your organisations or target group does this partnership answer, and how do you know?',
    type: 'textarea',
    next: 'objectives',
  },
  {
    id: 'objectives',
    formSection: 'What & How',
    formFieldLabel: 'Objectives',
    question: 'List a small number of SMART objectives that match the lump-sum scale.',
    type: 'textarea',
    next: 'activities',
  },
  {
    id: 'activities',
    formSection: 'Activities',
    formFieldLabel: 'Activities',
    question: 'What will you actually do together (meetings, training, local activities, a shared output)?',
    type: 'textarea',
    next: 'results',
  },
  {
    id: 'results',
    formSection: 'What & How',
    formFieldLabel: 'Results',
    question: 'What reusable result will exist at the end (toolkit, method, local practice)?',
    type: 'textarea',
    next: 'impact',
  },
  {
    id: 'impact',
    formSection: 'Impact',
    formFieldLabel: 'Impact and sharing',
    question: 'Who benefits, how will you share results locally, and how will you know it worked?',
    type: 'textarea',
    next: 'management',
  },
  {
    id: 'management',
    formSection: 'Management',
    formFieldLabel: 'Roles',
    question: 'Who does what, and how will you coordinate with a small partnership?',
    type: 'textarea',
    next: null,
  },
]

export const ka210Graph = defineGraph('summary', questions)
