import { defineGraph } from '../grantGraph'
import type { InterviewQuestion } from '../types'

const questions: InterviewQuestion[] = [
  {
    id: 'summary',
    formSection: 'Project description',
    formFieldLabel: 'Project summary',
    question: 'What is this cooperation partnership about?',
    helpText: 'KA220 is a larger transnational partnership with work packages and shared results — not a mobility project.',
    type: 'textarea',
    next: 'field',
  },
  {
    id: 'field',
    formSection: 'Project description',
    formFieldLabel: 'Field',
    question: 'Which field will you apply under?',
    type: 'select',
    options: [
      { value: 'youth', label: 'Youth' },
      { value: 'school', label: 'School education' },
      { value: 'vet', label: 'VET' },
      { value: 'adult', label: 'Adult education' },
      { value: 'higher', label: 'Higher education' },
    ],
    next: 'partners',
  },
  {
    id: 'partners',
    formSection: 'Partnership',
    formFieldLabel: 'Consortium',
    question: 'How many partners, from which countries, and who coordinates?',
    helpText: 'You need organisations from at least two Programme countries at application stage.',
    type: 'textarea',
    next: 'partner_roles',
  },
  {
    id: 'partner_roles',
    formSection: 'Partnership',
    formFieldLabel: 'Partner roles',
    question: 'Why these partners, and what does each one contribute (expertise, target group, delivery)?',
    type: 'textarea',
    next: 'duration',
  },
  {
    id: 'duration',
    formSection: 'Activities',
    formFieldLabel: 'Duration',
    question: 'Project length and planned start (typically 12–36 months).',
    type: 'text',
    next: 'priority',
  },
  {
    id: 'priority',
    formSection: 'Priorities',
    formFieldLabel: 'Priorities',
    question: 'Which horizontal and sectoral priorities will you address — and how do the activities actually deliver them?',
    type: 'textarea',
    next: 'needs',
  },
  {
    id: 'needs',
    formSection: 'Needs analysis',
    formFieldLabel: 'Needs',
    question: 'What need does the partnership address, with evidence per organisation or target group?',
    type: 'textarea',
    next: 'objectives',
  },
  {
    id: 'objectives',
    formSection: 'What & How',
    formFieldLabel: 'Objectives',
    question: 'SMART objectives chained to those needs. Same list everywhere in the application.',
    type: 'textarea',
    next: 'work_packages',
  },
  {
    id: 'work_packages',
    formSection: 'Activities',
    formFieldLabel: 'Work packages',
    question: 'Outline the work packages: purpose, lead partner, main tasks, and timing.',
    type: 'textarea',
    next: 'results',
  },
  {
    id: 'results',
    formSection: 'What & How',
    formFieldLabel: 'Results and outputs',
    question: 'What concrete results will exist, who can reuse them, and under what licence or access?',
    type: 'textarea',
    next: 'impact',
  },
  {
    id: 'impact',
    formSection: 'Impact',
    formFieldLabel: 'Impact',
    question: 'Impact on participating organisations, target groups, and (realistically) the field. Indicators and timeframe.',
    type: 'textarea',
    next: 'dissemination',
  },
  {
    id: 'dissemination',
    formSection: 'Impact',
    formFieldLabel: 'Dissemination and sustainability',
    question: 'Who will you reach, how, when — and what continues after EU funding ends (this project’s results, not leftover text)?',
    type: 'textarea',
    next: 'management',
  },
  {
    id: 'management',
    formSection: 'Management',
    formFieldLabel: 'Management and quality',
    question: 'Coordination, decision-making, quality assurance, risk, and how you will monitor the work packages.',
    type: 'textarea',
    next: 'budget',
  },
  {
    id: 'budget',
    formSection: 'Management',
    formFieldLabel: 'Budget logic',
    question: 'Which lump-sum / work-package budget are you aiming for, and why is it proportionate to the work?',
    type: 'textarea',
    next: null,
  },
]

export const ka220Graph = defineGraph('summary', questions)
