import { defineGraph } from '../grantGraph'
import type { InterviewQuestion } from '../types'

const questions: InterviewQuestion[] = [
  {
    id: 'summary',
    formSection: 'Relevance',
    formFieldLabel: 'Project summary',
    question: 'In a few sentences, what is this youth project about?',
    type: 'textarea',
    next: 'applicant',
  },
  {
    id: 'applicant',
    formSection: 'Relevance',
    formFieldLabel: 'Applicant',
    question: 'Who is applying (organisation type, country), and who are the partners?',
    type: 'textarea',
    next: 'beneficiary_check',
  },
  {
    id: 'beneficiary_check',
    formSection: 'Relevance',
    formFieldLabel: 'Primary participants',
    question: 'Who are the primary participants of the activity itself?',
    helpText: 'For KA153 this must be youth workers, not young people. Young people benefit afterwards through better youth work.',
    type: 'select',
    options: [
      { value: 'young_people', label: 'Young people (typically 13–30)' },
      { value: 'youth_workers', label: 'Youth workers / youth-work staff' },
      { value: 'mixed', label: 'A mix — explain in the next answer' },
    ],
    next: 'needs',
  },
  {
    id: 'needs',
    formSection: 'Relevance',
    formFieldLabel: 'Needs',
    question: 'What need does this respond to, and how do you know (method, when, who you asked)?',
    helpText: 'For KA153, needs must be at youth-worker and organisation level, not “young people use social media”.',
    type: 'textarea',
    next: 'eu_priorities',
  },
  {
    id: 'eu_priorities',
    formSection: 'Relevance',
    formFieldLabel: 'Priorities and Youth Goals',
    question: 'Which EU youth priorities or Youth Goals do the activities actually deliver — not only tick?',
    type: 'textarea',
    next: 'participant_count',
  },
  {
    id: 'participant_count',
    formSection: 'Quality of project design',
    formFieldLabel: 'Numbers and profile',
    question: 'How many people, from which countries, and how will you select them?',
    type: 'textarea',
    next: 'fewer_opportunities',
  },
  {
    id: 'fewer_opportunities',
    formSection: 'Quality of project design',
    formFieldLabel: 'Fewer opportunities',
    question: 'Will participants with fewer opportunities take part? Which barriers, and what support?',
    type: 'textarea',
    next: 'venue',
  },
  {
    id: 'venue',
    formSection: 'Quality of project design',
    formFieldLabel: 'Where and when',
    question: 'Where will it take place, why that venue, and what are the dates?',
    helpText: 'Venue should be in a participating organisation’s country.',
    type: 'textarea',
    next: 'activities',
  },
  {
    id: 'activities',
    formSection: 'Quality of project design',
    formFieldLabel: 'Programme',
    question: 'Outline the activity programme (non-formal methods, day-by-day if you can). Is there an APV?',
    helpText: 'An APV without a session plan will not be funded.',
    type: 'textarea',
    next: 'methods',
  },
  {
    id: 'methods',
    formSection: 'Quality of project design',
    formFieldLabel: 'Non-formal methods',
    question: 'Which non-formal methods will you use, and how do they match the learning outcomes?',
    type: 'textarea',
    next: 'apv',
  },
  {
    id: 'apv',
    formSection: 'Quality of project design',
    formFieldLabel: 'Preparatory visit',
    question: 'Are you requesting a preparatory visit?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes — we have a day-by-day APV programme' },
      { value: 'no', label: 'No' },
    ],
    next: 'objectives',
    branches: [
      { equals: 'yes', goto: 'apv_programme' },
      { equals: 'no', goto: 'objectives' },
    ],
  },
  {
    id: 'apv_programme',
    formSection: 'Annexes',
    formFieldLabel: 'APV programme',
    question: 'Paste or describe the APV session plan (who, when, what each session is for).',
    type: 'textarea',
    next: 'objectives',
  },
  {
    id: 'objectives',
    formSection: 'Quality of project design',
    formFieldLabel: 'Objectives',
    question: 'List SMART objectives that follow from the needs. Same numbers and titles in every section.',
    type: 'textarea',
    next: 'learning_outcomes',
  },
  {
    id: 'learning_outcomes',
    formSection: 'Quality of project design',
    formFieldLabel: 'Learning outcomes',
    question: 'Knowledge, skills and attitudes. For KA153 these must be usable in daily youth work.',
    type: 'textarea',
    next: 'youthpass',
  },
  {
    id: 'youthpass',
    formSection: 'Quality of project design',
    formFieldLabel: 'Recognition',
    question: 'How will learning be recognised (Youthpass, reflection sessions, certificates)?',
    type: 'textarea',
    next: 'preparation',
  },
  {
    id: 'preparation',
    formSection: 'Quality of project design',
    formFieldLabel: 'Preparation, implementation, follow-up',
    question: 'What happens before, during and after — who does what, and how is each phase evaluated?',
    type: 'textarea',
    next: 'timetable',
  },
  {
    id: 'timetable',
    formSection: 'Annexes',
    formFieldLabel: 'Day-by-day timetable',
    question: 'Paste or outline the day-by-day session plan for the main activity (and APV if requested).',
    helpText: 'Reviewers will not fund an activity or APV without a session programme.',
    type: 'textarea',
    next: 'impact',
  },
  {
    id: 'impact',
    formSection: 'Quality of project management',
    formFieldLabel: 'Impact and dissemination',
    question: 'Impact at the real scale of the activity, with target groups, channels, timeline and indicators.',
    type: 'textarea',
    next: 'safety',
  },
  {
    id: 'safety',
    formSection: 'Quality of project management',
    formFieldLabel: 'Safety and insurance',
    question: 'What safety, insurance, and safeguarding measures apply to participants?',
    type: 'textarea',
    next: 'evaluation',
  },
  {
    id: 'evaluation',
    formSection: 'Quality of project management',
    formFieldLabel: 'Evaluation',
    question: 'How will you evaluate each phase, and which indicators match the real participant numbers?',
    type: 'textarea',
    next: 'management',
  },
  {
    id: 'management',
    formSection: 'Quality of project management',
    formFieldLabel: 'Management',
    question: 'Roles, communication, and how you will keep one project identity (title, numbers, objectives).',
    type: 'textarea',
    next: null,
  },
]

export const kaYouthGraph = defineGraph('summary', questions)
