import { defineGraph } from '../grantGraph'
import type { InterviewQuestion } from '../types'

const questions: InterviewQuestion[] = [
  {
    id: 'youth_action',
    formSection: 'Project description',
    formFieldLabel: 'Youth action',
    question: 'Which youth action is this?',
    helpText: 'KA152 = young people as participants. KA153 = youth workers. KA154 = youth participation activities.',
    type: 'select',
    options: [
      { value: 'ka152', label: 'KA152 — Youth exchanges' },
      { value: 'ka153', label: 'KA153 — Mobility of youth workers' },
      { value: 'ka154', label: 'KA154 — Youth participation activities' },
    ],
    next: 'summary',
    branches: [
      { equals: 'ka152', goto: 'summary' },
      { equals: 'ka153', goto: 'summary' },
      { equals: 'ka154', goto: 'summary' },
    ],
  },
  {
    id: 'summary',
    formSection: 'Project description',
    formFieldLabel: 'Project summary',
    question: 'In a few sentences, what is this youth project about?',
    type: 'textarea',
    next: 'applicant',
  },
  {
    id: 'applicant',
    formSection: 'Participating organisation',
    formFieldLabel: 'Applicant',
    question: 'Who is applying (organisation type, country), and who are the partners?',
    type: 'textarea',
    next: 'beneficiary_check',
  },
  {
    id: 'beneficiary_check',
    formSection: 'Participants',
    formFieldLabel: 'Primary participants',
    question: 'Who are the primary participants of the activity itself?',
    helpText: 'For KA153 this must be youth workers, not young people. Young people benefit afterwards through better youth work.',
    type: 'select',
    options: [
      { value: 'young_people', label: 'Young people (typically 13–30)' },
      { value: 'youth_workers', label: 'Youth workers / youth-work staff' },
      { value: 'mixed', label: 'A mix — explain in the next answer' },
    ],
    next: 'participant_count',
  },
  {
    id: 'participant_count',
    formSection: 'Participants',
    formFieldLabel: 'Numbers and profile',
    question: 'How many people, from which countries, and how will you select them?',
    type: 'textarea',
    next: 'fewer_opportunities',
  },
  {
    id: 'fewer_opportunities',
    formSection: 'Participants',
    formFieldLabel: 'Fewer opportunities',
    question: 'Will participants with fewer opportunities take part? Which barriers, and what support?',
    type: 'textarea',
    next: 'needs',
  },
  {
    id: 'needs',
    formSection: 'Needs analysis',
    formFieldLabel: 'Needs',
    question: 'What need does this respond to, and how do you know (method, when, who you asked)?',
    helpText: 'For KA153, needs must be at youth-worker and organisation level, not “young people use social media”.',
    type: 'textarea',
    next: 'venue',
  },
  {
    id: 'venue',
    formSection: 'Activities',
    formFieldLabel: 'Where and when',
    question: 'Where will it take place, why that venue, and what are the dates?',
    helpText: 'Venue should be in a participating organisation’s country.',
    type: 'textarea',
    next: 'activities',
  },
  {
    id: 'activities',
    formSection: 'Activities',
    formFieldLabel: 'Programme',
    question: 'Outline the activity programme (non-formal methods, day-by-day if you can). Is there an APV?',
    helpText: 'An APV without a session plan will not be funded.',
    type: 'textarea',
    next: 'apv',
  },
  {
    id: 'apv',
    formSection: 'Activities',
    formFieldLabel: 'Preparatory visit',
    question: 'Are you requesting a preparatory visit?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes — we have a day-by-day APV programme' },
      { value: 'no', label: 'No' },
    ],
    next: 'objectives',
    branches: [
      { equals: 'yes', goto: 'apv_programme' },
      { equals: 'no', goto: 'objectives' },
    ],
  },
  {
    id: 'apv_programme',
    formSection: 'Activities',
    formFieldLabel: 'APV programme',
    question: 'Paste or describe the APV session plan (who, when, what each session is for).',
    type: 'textarea',
    next: 'objectives',
  },
  {
    id: 'objectives',
    formSection: 'What & How',
    formFieldLabel: 'Objectives',
    question: 'List SMART objectives that follow from the needs. Same numbers and titles in every section.',
    type: 'textarea',
    next: 'learning_outcomes',
  },
  {
    id: 'learning_outcomes',
    formSection: 'What & How',
    formFieldLabel: 'Learning outcomes',
    question: 'Knowledge, skills and attitudes. For KA153 these must be usable in daily youth work.',
    type: 'textarea',
    next: 'preparation',
  },
  {
    id: 'preparation',
    formSection: 'What & How',
    formFieldLabel: 'Preparation, implementation, follow-up',
    question: 'What happens before, during and after — who does what, and how is each phase evaluated?',
    type: 'textarea',
    next: 'impact',
  },
  {
    id: 'impact',
    formSection: 'Impact',
    formFieldLabel: 'Impact and dissemination',
    question: 'Impact at the real scale of the activity, with target groups, channels, timeline and indicators.',
    type: 'textarea',
    next: 'management',
  },
  {
    id: 'management',
    formSection: 'Management',
    formFieldLabel: 'Management',
    question: 'Roles, safety/insurance, communication, and how you will keep one project identity (title, numbers, objectives).',
    type: 'textarea',
    next: null,
  },
]

export const kaYouthGraph = defineGraph('youth_action', questions)
